[workspace]
members = ["."]

[toolchain]
anchor_version = "0.24.2"
solana_version = "1.9.13"

[features]
resolution = true
skip-lint = false

[programs.localnet]
abc_token = "vBcHBCoQLGDvKejC5MHEZW4pLZi17FS8qPtyA2S6NVt"

[programs.testnet]
abc_token = "vBcHBCoQLGDvKejC5MHEZW4pLZi17FS8qPtyA2S6NVt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "testnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
